FROM --platform=x86_64 node:18

WORKDIR /app

COPY poi-relayer/package.json .

RUN yarn

COPY poi-relayer/. .
COPY start-relayer.sh .

EXPOSE 8000

HEALTHCHECK CMD curl http://localhost:8000/status

RUN chmod +x start-relayer.sh

CMD yarn
